# Lab | Data Structuring and Combining Data

## Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

In [39]:
import pandas as pd
import numpy as np
import os
data2=pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv")
data3=pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv")

In [40]:
data_main=pd.read_excel("data_check.xlsx")
data_main

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,QZ44356,Arizona,F,Bachelor,697953.59,0,94,0,Personal Auto,Four-Door Car,1131.464935
1,AI49188,Nevada,F,Bachelor,1288743.17,48767,108,0,Personal Auto,Two-Door Car,566.472247
2,WW63253,California,M,Bachelor,764586.18,0,106,0,Corporate Auto,SUV,529.881344
3,GA49547,Washington,M,High School or Below,536307.65,36357,68,0,Personal Auto,Four-Door Car,17.269323
4,OC83172,Oregon,F,Bachelor,825629.78,62902,69,0,Personal Auto,Two-Door Car,159.383042
...,...,...,...,...,...,...,...,...,...,...,...
1065,TM65736,Oregon,M,Master,305955.03,38644,78,1,Personal Auto,Four-Door Car,361.455219
1066,VJ51327,Cali,F,High School or Below,2031499.76,63209,102,2,Personal Auto,SUV,207.320041
1067,GS98873,Arizona,F,Bachelor,323912.47,16061,88,0,Personal Auto,Four-Door Car,633.600000
1068,CW49887,California,F,Master,462680.11,79487,114,0,Special Auto,SUV,547.200000
1069,MY31220,California,F,College,899704.02,54230,112,0,Personal Auto,Two-Door Car,537.600000

In [41]:
#filepath= "checkmain/transfer_data.pkl"
#initial_data=pd.read_pickle(filepath)

In [42]:
# 1 Cleaning invalid values for Data2
data2.columns=data2.columns.str.strip().str.lower().str.replace(' ', '_')
data2.rename(columns={"st":"state"}, inplace=True)
data2["gender"]=data2["gender"].replace({"Male":"M","female":"F","Femal":"F"})
data2["education"]=data2["education"].replace({"Bachelors":"Bachelor"})
data2["customer_lifetime_value"]=data2["customer_lifetime_value"].str.replace("%","")
data2["vehicle_class"]=data2["vehicle_class"].replace({"Sports Car":"luxury","Luxury SUV":"luxury","Luxury Car":"luxury"})

In [43]:
# 2 Formating data types
data2["customer_lifetime_value"]=pd.to_numeric(data2["customer_lifetime_value"])
data2["number_of_open_complaints"]=data2["number_of_open_complaints"].str.split("/").str[1]
data2["number_of_open_complaints"]=pd.to_numeric(data2["number_of_open_complaints"],errors="coerce")
data2.describe()

,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,total_claim_amount
count,9.920000e+02,996.000000,996.000000,996.000000,996.000000
mean,7.651494e+05,39764.920683,143.347390,0.368474,417.609099
std,6.214653e+05,30203.714667,572.289901,0.888661,271.928647
min,2.004351e+05,0.000000,61.000000,0.000000,1.687291
25%,3.924119e+05,16505.500000,68.000000,0.000000,278.794307
50%,5.627054e+05,36533.000000,80.000000,0.000000,350.400000
75%,8.690526e+05,63540.000000,107.000000,0.000000,513.339366
max,4.922143e+06,99981.000000,7575.000000,5.000000,2201.327879

In [44]:
# 3 Handling Null values
data2=data2.ffill()
data2=data2.dropna(subset=["gender","customer_lifetime_value"])
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 996 entries, 0 to 995
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   996 non-null    object
 1   state                      996 non-null    object
 2   gender                     996 non-null    object
 3   education                  996 non-null    object
 4   customer_lifetime_value    996 non-null    float64
 5   income                     996 non-null    int64
 6   monthly_premium_auto       996 non-null    int64
 7   number_of_open_complaints  996 non-null    int64
 8   total_claim_amount         996 non-null    float64
 9   policy_type                996 non-null    object
 10  vehicle_class              996 non-null    object
dtypes: float64(2), int64(3), object(6)
memory usage: 85.7+ KB

In [45]:
# 4 Dealing with duplicates
data2=data2.drop_duplicates()
data2=data2.reset_index(drop=True)
data2.duplicated().sum()

0

In [60]:
# 1 Cleaning invalid values for Data3
data3.columns=data3.columns.str.strip().str.lower().str.replace(' ', '_')
data3.rename(columns={"st":"state"}, inplace=True)
data3["gender"]=data3["gender"].replace({"Male":"M","female":"F","Femal":"F"})
data3["education"]=data3["education"].replace({"Bachelors":"Bachelor"})
data3["vehicle_class"]=data3["vehicle_class"].replace({"Sports Car":"luxury","Luxury SUV":"luxury","Luxury Car":"luxury"})

In [65]:
# 2 Handling Null values
data3=data3.ffill()
data3=data3.dropna(subset=["gender","customer_lifetime_value"])
data3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7070 entries, 0 to 7069
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   7070 non-null   object
 1   state                      7070 non-null   object
 2   customer_lifetime_value    7070 non-null   float64
 3   education                  7070 non-null   object
 4   gender                     7070 non-null   object
 5   income                     7070 non-null   int64
 6   monthly_premium_auto       7070 non-null   int64
 7   number_of_open_complaints  7070 non-null   int64
 8   policy_type                7070 non-null   object
 9   total_claim_amount         7070 non-null   float64
 10  vehicle_class              7070 non-null   object
dtypes: float64(2), int64(3), object(6)
memory usage: 607.7+ KB

In [66]:
# 4 Dealing with duplicates
data3=data3.drop_duplicates()
data3=data3.reset_index(drop=True)
data3.duplicated().sum()

0

In [67]:
data3.describe(include="number")

,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,total_claim_amount
count,7070.000000,7070.000000,7070.000000,7070.000000,7070.000000
mean,8028.803803,37333.857709,93.199010,0.384300,436.215960
std,6942.419253,30349.879656,34.210682,0.915658,291.236837
min,1898.007675,0.000000,61.000000,0.000000,0.099007
25%,3981.073024,0.000000,68.000000,0.000000,274.363620
50%,5782.095838,33557.500000,83.000000,0.000000,386.031248
75%,8989.995803,61895.500000,109.000000,0.000000,552.000000
max,83325.381190,99961.000000,298.000000,5.000000,2759.794354

In [72]:
main_data=pd.concat([data_main,data2,data3],axis=0)
main_data

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,QZ44356,Arizona,F,Bachelor,6.979536e+05,0,94,0,Personal Auto,Four-Door Car,1131.464935
1,AI49188,Nevada,F,Bachelor,1.288743e+06,48767,108,0,Personal Auto,Two-Door Car,566.472247
2,WW63253,California,M,Bachelor,7.645862e+05,0,106,0,Corporate Auto,SUV,529.881344
3,GA49547,Washington,M,High School or Below,5.363077e+05,36357,68,0,Personal Auto,Four-Door Car,17.269323
4,OC83172,Oregon,F,Bachelor,8.256298e+05,62902,69,0,Personal Auto,Two-Door Car,159.383042
...,...,...,...,...,...,...,...,...,...,...,...
7065,LA72316,California,M,Bachelor,2.340599e+04,71941,73,0,Personal Auto,Four-Door Car,198.234764
7066,PK87824,California,F,College,3.096511e+03,21604,79,0,Corporate Auto,Four-Door Car,379.200000
7067,TD14365,California,M,Bachelor,8.163890e+03,0,85,3,Corporate Auto,Four-Door Car,790.784983
7068,UP19263,California,M,College,7.524442e+03,21941,96,0,Personal Auto,Four-Door Car,691.200000
7069,Y167826,California,M,College,2.611837e+03,0,77,0,Corporate Auto,Two-Door Car,369.600000

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [117]:
market=pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv")
market

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,A,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10905,10905,FE99816,Nevada,15563.369440,No,Premium,Bachelor,2011-01-19,Unemployed,F,...,7,Personal Auto,Personal L1,Offer3,Web,1214.400000,Luxury Car,Medsize,A,1
10906,10906,KX53892,Oregon,5259.444853,No,Basic,College,2011-01-06,Employed,F,...,6,Personal Auto,Personal L3,Offer2,Branch,273.018929,Four-Door Car,Medsize,A,1
10907,10907,TL39050,Arizona,23893.304100,No,Extended,Bachelor,2011-02-06,Employed,F,...,2,Corporate Auto,Corporate L3,Offer1,Web,381.306996,Luxury SUV,Medsize,A,2
10908,10908,WA60547,California,11971.977650,No,Premium,College,2011-02-13,Employed,F,...,6,Personal Auto,Personal L1,Offer1,Branch,618.288849,SUV,Medsize,A,2
10909,10909,IV32877,California,6857.519928,No,Basic,Bachelor,2011-01-08,Unemployed,M,...,3,Personal Auto,Personal L1,Offer4,Web,1021.719397,SUV,Medsize,A,1

In [118]:
market.rename(columns={"employmentstatus":"employment status"}, inplace =True)

In [119]:
#Drop the extra index column
market=market.drop(columns=["unnamed:_0"])

In [127]:
market

,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employment status,gender,income,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,48029,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,0,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1
2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,22139,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,49078,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,23675,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,A,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10905,FE99816,Nevada,15563.369440,No,Premium,Bachelor,2011-01-19,Unemployed,F,0,...,7,Personal Auto,Personal L1,Offer3,Web,1214.400000,Luxury Car,Medsize,A,1
10906,KX53892,Oregon,5259.444853,No,Basic,College,2011-01-06,Employed,F,61146,...,6,Personal Auto,Personal L3,Offer2,Branch,273.018929,Four-Door Car,Medsize,A,1
10907,TL39050,Arizona,23893.304100,No,Extended,Bachelor,2011-02-06,Employed,F,39837,...,2,Corporate Auto,Corporate L3,Offer1,Web,381.306996,Luxury SUV,Medsize,A,2
10908,WA60547,California,11971.977650,No,Premium,College,2011-02-13,Employed,F,64195,...,6,Personal Auto,Personal L1,Offer1,Branch,618.288849,SUV,Medsize,A,2
10909,IV32877,California,6857.519928,No,Basic,Bachelor,2011-01-08,Unemployed,M,0,...,3,Personal Auto,Personal L1,Offer4,Web,1021.719397,SUV,Medsize,A,1

In [154]:
market.columns

Index(['customer', 'state', 'customer_lifetime_value', 'response', 'coverage',
       'education', 'effective_to_date', 'employment status', 'gender',
       'income', 'location_code', 'marital_status', 'monthly_premium_auto',
       'months_since_last_claim', 'months_since_policy_inception',
       'number_of_open_complaints', 'number_of_policies', 'policy_type',
       'policy', 'renew_offer_type', 'sales_channel', 'total_claim_amount',
       'vehicle_class', 'vehicle_size', 'vehicle_type', 'month'],
      dtype='object')

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

In [142]:
market_rev=round(market.pivot_table(columns="sales_channel", values=["income"], aggfunc="sum"),2)
market_rev

sales_channel      Agent     Branch  Call Center       Web
income         152490152  113775608     81055004  62200103

Marketing campaigns done by agents and at the various branches appear to generate the highest revenue.

In [143]:
market_rev2=round(market.pivot_table(index="state", columns="sales_channel", values=["income"], aggfunc="sum"),2)
market_rev2

                 income
sales_channel     Agent    Branch Call Center       Web
state
Arizona        26402332  19913698    15823934  10277955
California     58715264  44330409    29492342  24210886
Nevada         14092700  10548842     7571634   5946977
Oregon         40168451  29709695    21768398  17130619
Washington     13111405   9272964     6398696   4633666

Marketing campaign done by agents and also at the branches also appeared to generate the highest income 
across the states.

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

In [148]:
market_clv=round(market.pivot_table(index="gender", columns="education", values=["customer_lifetime_value"]),2)
market_clv

          customer_lifetime_value                                         \
education                Bachelor  College   Doctor High School or Below
gender
F                         7874.27  7748.82  7328.51              8675.22
M                         7703.60  8052.46  7415.33              8149.69


education   Master
gender
F          8157.05
M          8168.83

The customer life time value for both male and female customers appear to be higher for customers in 
high-school and below, and also for highly educated customers with a masters degree.

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [158]:
market_comp=round(market.groupby(["policy_type","month"]).agg({"number_of_open_complaints":"sum"}),2)
market_comp

                      number_of_open_complaints
policy_type    month
Corporate Auto 1                         443.43
               2                         385.21
Personal Auto  1                        1727.61
               2                        1453.68
Special Auto   1                          87.07
               2                          95.23

Personal auto had the highest number of complaints in general but in month 1 recored the highest complaints compared to month 1.